name: airspace
channels:
  - defaults
dependencies:
  - fiona
  - pandas
  - pip
  - matplotlib
  - python=3.6
  - numba
  - numpy
  - geopandas
  - jupyter
  - seaborn
  - requests
  - pip:
    - p-tqdm==1.3.3
    - geopy==1.22.0
